version: '2'
services:
  rssserver:
    #build: ./server
    image: tianyuliufang/rsswebserver
    volumes:
      - ./server/config.yaml:/app/config.yaml
      - ./server/resource/:/app/resource/
    ports:
      - "9000:8888"
    logging:
      options: 
        max-size: "1g"
  rssweb:
    #build: ./web
    image: tianyuliufang/rsswebstatic
    volumes:
      - ./server.conf:/etc/nginx/conf.d/default.conf
      #- ./web/dist/:/app/
    ports:
      - "9001:80"
    logging:
      options: 
        max-size: "1g"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: miniflux
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - /data/postgresql:/var/lib/postgresql/data/
    ports:
      - "9002:5432"
  redis:
    image: redis:latest
  huginn:
    image: huginn/huginn:latest
    ports:
      - "9003:3000"
    environment:
      - POSTGRES_PORT_5432_TCP_ADDR=db
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - HUGINN_DATABASE_USERNAME=miniflux
      - HUGINN_DATABASE_PASSWORD=secret
      - HUGINN_DATABASE_ADAPTER=postgresql
      - HUGINN_DATABASE_NAME=huginn
    logging:
      options: 
        max-size: "1g"
