from node:12.18.4  as build
WORKDIR /usr/src/app
copy . .
workdir /usr/src/app/web
run npm install -g cnpm --registry=https://registry.npm.taobao.org && npm cache clean --force && cnpm install &&cnpm install @vue/cli-service -g && cnpm install --save-dev script-ext-html-webpack-plugin vue-template-compiler @vue/cli-plugin-eslint @vue/cli-plugin-babel  && npm run build

from nginx:latest
workdir /app/
copy --from=build ["/usr/src/app/web/dist/","./"]
workdir /etc/nginx/conf.d/
copy --from=build ["/usr/src/app/server.conf","./"]
expose 80
