FROM node:12.18.4  as build
WORKDIR /usr/src/app
RUN git clone -b rssweb https://gitee.com/null_312_2255/rssweb.git rssweb
WORKDIR /usr/src/app/rssweb/web
RUN npm cache clean --force && npm install &&npm install @vue/cli-service -g && npm install --save-dev script-ext-html-webpack-plugin vue-template-compiler @vue/cli-plugin-eslint @vue/cli-plugin-babel  && npm run build

FROM nginx:latest
WORKDIR /app/
COPY --from=build ["/usr/src/app/rssweb/web/dist/","./"]
WORKDIR /etc/nginx/conf.d/
COPY --from=build ["/usr/src/app/rssweb/server.conf","./"]
EXPOSE 80
