FROM golang:1.15  as build
WORKDIR /go/src/app
ARG GO111MODULE=on
ARG GOPROXY='https://goproxy.cn'
RUN git clone -b rssweb https://gitee.com/null_312_2255/rssweb.git rssweb
RUN pwd
WORKDIR /go/src/app/rssweb/server
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go 
RUN ls -al . 
RUN pwd

FROM alpine:latest
WORKDIR /app/
COPY --from=build /go/src/app/rssweb/server/config.yaml .
COPY --from=build /go/src/app/rssweb/server/main .
COPY --from=build /go/src/app/rssweb/server/resource ./resource

RUN ls -al
RUN chmod +x main
EXPOSE 8888
CMD ["./main"]
