# testproject Global Configuration

# jwt configuration
jwt:
  signing-key: 'qmPlus'

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[testproject]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
redis:
  db: 0
  addr: '192.168.3.121:30002'
  password: ''

# email configuration

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: 'postgres'
  oss-type: 'local'
  use-multipoint: true # 是否开启redis

# captcha configuration
captcha:
  key-long: 1
  img-width: 240
  img-height: 80

# mysql connect configuration
#mysql:
#  path: '192.168.3.121:3306'
#  config: 'charset=utf8mb4&parseTime=True&loc=Local'
#  db-name: 'qmPlus'
#  username: 'root'
#  password: 'Aa@6447985'
#  max-idle-conns: 10
#  max-open-conns: 100
#  log-mode: false
#  log-zap: false
pg:
  host: '192.168.3.121'
  port: '30001'
  username: 'db'
  password: 'Aa123456'
  dbname: 'testdb'
  sslmode: disable
  timezone: 'Asia/Shanghai'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: false


# local configuration
local:
  path: 'uploads/file'